- hosts: webservers
  become: yes
  vars:
    http_port: 8000
    http_port: 4443 
    html_welcome_msg: 'Hello world'
  tasks:
      
      name: ensure apache is unsatall
      apt:
        
        name: apache2
        state: latest        
